
- name: creating user with error handling
  hosts: web
  become: yes
  tasks:
    - name: checking user status (Will fail if user 'expense' doesn't exist)
      # Using 'command' module to run the 'id' command
      ansible.builtin.command: id expense
      
      # CRITICAL FIX: The parameter must be 'register'
      register: USER

- name: creating user with error handling
  hosts: web
  become: yes
  tasks:
    - name: checking user status
      ansible.builtin.command: id expense
      registers: USER
  