- name: Working on Functions
  hosts: web
  become: yes
  tasks:
    - name: prining default Functions
      ansible.builtin.debug:
        msg: "{{ name | default('fucking ansible') }}"
    - name: Converting string to uppder case and lower case
      vars:
        name: " Hello Fucking Ansible"
      ansible.builtin.debug:
        msg: "upper case: {{ name | upper }}, lower caase: {{name| lower}}"

    - name: Unique numbers in a list
      vars:
        num: [1,2,3,55,69,1,2,55]
      ansible.builtin.debug:
        msg: "unique number: {{ num | unique }}"