- name: Removing packages
  hosts: web
  tasks:
   - name: Removing mysql
     ansible.builtin.package:
       name: mysql
       state: absent
- name: Removing packages
  hosts: web
  tasks:
    - name: REMOVING nginx
      ansible.builtin.pacakge:
        name: nginx
        state: absent