- name: Variables
  hosts: web
  vars:
    - name: "Ganesh"
      Goal: "job switch to devops"
      Course: "next month 15"
  tasks:
  - name: Printing names using Variables
    ansible.builtin.debug:
     msg: "Hello {{Name}} and my goal is {{Goal}} in {{Course}}"
  - name: printing names again

    ansible.builtin.debug:
     msg: "Hello {{Name}} and my goal is {{Goal}} in {{Course}}"
