- name: Variables
  hosts: web
  vars:
   Name: "Ganesh"
   Goal: "job switch to devops"
  tasks:
  - name: Printing names using Variables
    ansible.builtin.debug:
     msg: "Hello {{Namre}} and my goal is {{Goal}}"