- name: Variables
  hosts: web
  vars:
      pName: "Ganesh"
      pGoal: "job switch to devops"
      pCourse: "next month 15"
  tasks:
  - name: Printing names using Variables
    ansible.builtin.debug:
     msg: "Hello {{pName}} and my goal is {{pGoal}} in {{pCourse}}"
  - name: printing names again
    ansible.builtin.debug:
     msg: "Hello {{Name}} and my goal is {{Goal}} in {{Course}}"
